# Generated by Django 5.2.2 on 2025-09-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_apiuser_created_apiuser_last_accessed"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="braze_id",
            field=models.UUIDField(blank=True, help_text="The ID for the subscription group in Braze", null=True, unique=True),
        ),
    ]
