# Generated by Django 5.2.2 on 2025-09-24 09:41

from django.db import migrations, models


def populate_braze_ids(apps, schema_editor):
    Newsletter = apps.get_model("news", "Newsletter")
    braze_mapping = {
        "mozilla-and-you": "96f6577e-6efd-4744-9d96-dbe67b1f48c5",
        "mozilla-foundation": "c7349bcb-0aae-43d6-a8ef-fc8d5cf68a99",
    }
    for newsletter in Newsletter.objects.all():
        newsletter.braze_id = braze_mapping.get(newsletter.slug, None)
        newsletter.save(update_fields=["braze_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_apiuser_created_apiuser_last_accessed"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="braze_id",
            field=models.UUIDField(blank=True, help_text="The ID for the subscription group in Braze", null=True, unique=True),
        ),
        migrations.RunPython(populate_braze_ids, reverse_code=migrations.RunPython.noop),
    ]
