# Generated by Django 5.2.2 on 2025-10-03 16:47

from django.conf import settings
from django.db import migrations


def update_newsletter_vendor_ids(apps, schema_editor):
    """
    Updates the vendor_id column with the subscription_group_id used in Braze
    (dev or prod based on LOCAL_DEV env var).

    Map source:
    http://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/braze_derived/subscriptions_map_v1/script.sql
    """

    Newsletter = apps.get_model("news", "Newsletter")

    prod_slug_to_vendor_id = {
        "about-addons": "b9f6b780-8fc3-4eab-b033-10d4f5f7a370",
        "about-mozilla": "e23dfa20-6dd9-4a2f-a9cb-7bd2f8db5925",
        "antiharassment-waitlist": "ebe059f4-ab45-467e-9dfc-25094ca85a51",
        "app-dev": "3ade707a-e9de-4577-ab02-2ababbc669b5",
        "didthis-waitlist": "13d0a1e5-54eb-43bb-891d-f83576415fda",
        "firefox-accounts-journey": "21ae0bbb-56ab-4c3d-8add-005a23a9bc9a",
        "formulaic-app": "3349e1ab-acb8-4396-8fff-ee9d5cf96678",
        "graceland-waitlist": "0dd864a8-7afb-4e01-874c-5bd89c62f249",
        "guardian-vpn-waitlist": "755c3084-9124-44b9-bed0-3411ad7a02da",
        "knowledge-is-power": "f5486fa3-4e95-4fb7-9a14-e3fcd71e9c6c",
        "mdnplus": "d63436eb-2bf6-492f-a5c6-dc63c86f1711",
        "monitor-waitlist": "7ca5d9bb-758a-4a40-843b-8887b5c8ffaf",
        "mozilla-ai-challenge": "f0ee135a-eac2-4319-aede-f68d60c5e6d5",
        "mozilla-and-you": "b9ea49d0-ddd0-4db1-a390-7268e0498a24",
        "mozilla-builder": "7e8d71f9-2e26-4308-ac0f-05a591cbae5a",
        "mozilla-builders-application-2024": "d48a2578-4963-4ac9-9d4e-3005106a3606",
        "mozilla-innovation": "39fcaf11-2926-4366-b756-2c02e65cbce7",
        "mozilla-social-waitlist": "d64e060f-2955-4926-9e36-d54b5d784975",
        "nothing-personal-college-interest": "7edc5999-8893-4453-b4f3-70ab7c479dd2",
        "relay-phone-masking-waitlist": "4011707b-1a55-4177-9f5d-2a6d86225242",
        "relay-vpn-bundle-waitlist": "b0bffabc-a735-4c70-b48f-c788c42cc3f9",
        "relay-waitlist": "9f68d648-ac73-49bc-a94e-1c22191c49a9",
        "security-privacy-news": "3c2d58e5-dfaa-43ef-8e37-ae86a5db360d",
        "take-action-for-the-internet": "cd16fdf7-88bb-4ff3-a8d9-cc5102790f49",
        "ten-tabs": "5711f4ee-663a-4010-81e5-b087c273681c",
        "test-pilot": "7a6cc4c5-441e-4c3b-95a6-e9de7edc78fd",
    }

    dev_slug_to_vendor_id = {
        "about-addons": "56ad1633-dcc7-4841-aa4d-64026e4e17cb",
        "about-mozilla": "0d4f7b75-fb25-4db0-a83a-98cb3558e185",
        "antiharassment-waitlist": "a1e5b62d-eb64-4281-b8c6-0a7157905eb6",
        "app-dev": "23069735-6496-4a19-8240-b910f94660b0",
        "didthis-waitlist": "8d349590-84e1-44ef-bef8-c743f2429139",
        "firefox-accounts-journey": "e095ad1d-ce90-4d4e-981e-9afc2da22a21",
        "formulaic-app": "91f8d0bf-5d01-48b5-bcc4-e12373e3f89b",
        "graceland-waitlist": "2bd5aae2-a0c3-4d7c-9afa-5e8877549de2",
        "guardian-vpn-waitlist": "2a87f6bc-0028-4f2f-8d91-af253ad3cf14",
        "knowledge-is-power": "eb2208b3-5e7d-4d72-8e43-803a43373fb8",
        "mdnplus": "55dce620-720b-42e3-9d35-ab43de4e13c0",
        "monitor-waitlist": "791113d3-82e9-4e45-b4e0-5e7d3f815765",
        "mozilla-ai-challenge": "e49e6683-6e77-479d-a2ed-c9753989864c",
        "mozilla-and-you": "96f6577e-6efd-4744-9d96-dbe67b1f48c5",
        "mozilla-builder": "74435f4a-e25e-41bb-973a-a769179e05a0",
        "mozilla-builders-application-2024": "6fdbce2c-0110-4bd5-94ce-ff6f4e2ca905",
        "mozilla-innovation": "cfcd1d98-21f1-4485-8594-ebf68451ec2d",
        "mozilla-social-waitlist": "a0fc09f3-a0cd-4321-8325-6235cec6d162",
        "nothing-personal-college-interest": "c0681ddd-1ae8-49df-bffd-6f3e6dd0aa92",
        "relay-phone-masking-waitlist": "b9000bb3-7377-4908-9579-b0b7341aaad6",
        "relay-vpn-bundle-waitlist": "6eb4658e-f030-4b08-a763-0930ac1112eb",
        "relay-waitlist": "07feceb4-1db5-4ada-a559-5615063fbeca",
        "security-privacy-news": "288e2dbb-7f48-4b77-b238-8d8e1bd01810",
        "take-action-for-the-internet": "8627ca41-5358-4107-9d50-677ed31d57ff",
        "ten-tabs": "1da167f2-c473-4949-ac8e-0045ad5b23ff",
        "test-pilot": "1da52ebe-442e-41b5-bab2-dc293f559c66",
    }

    slug_to_vendor_id_ = prod_slug_to_vendor_id if getattr(settings, "LOCAL_DEV", False) else dev_slug_to_vendor_id

    for slug, vendor_id in slug_to_vendor_id_.items():
        Newsletter.objects.filter(slug=slug).update(vendor_id=vendor_id)


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_apiuser_created_apiuser_last_accessed"),
    ]

    operations = [
        migrations.RunPython(update_newsletter_vendor_ids),
    ]
